'use client'

import { useEffect, useState } from 'react'
import { useSearchParams } from 'next/navigation'
import { PageWrapper } from '@/components/layout/PageWrapper'
import { MarkdownViewer } from '@/components/report/MarkdownViewer'
import { InteractiveCharts } from '@/components/report/InteractiveCharts'
import { useExperimentStore } from '@/store/experimentStore'
import { airoApi } from '@/lib/api'
import { FileSearch, Loader2 } from 'lucide-react'
import Link from 'next/link'
import { Button } from '@/components/ui/button'
import { Suspense } from 'react'

function ReportContent() {
  const store = useExperimentStore()
  const searchParams = useSearchParams()
  const queryId = searchParams?.get('id')

  // The ID to fetch is either from URL query params, or the current active store
  const targetId = queryId || store.experimentId

  const [content, setContent] = useState<string | null>(null)
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState(false)

  useEffect(() => {
    if (!targetId) return

    setLoading(true)
    setError(false)
    
    airoApi.getReportMarkdown(targetId)
      .then(res => {
        setContent(res)
        setLoading(false)
      })
      .catch(() => {
        setError(true)
        setLoading(false)
      })
  }, [targetId])

  if (!targetId) {
    return (
      <PageWrapper>
        <div className="w-full max-w-4xl mx-auto mt-20 text-center">
          <div className="w-16 h-16 rounded-full bg-cyan-50 text-cyan-600 flex items-center justify-center mx-auto mb-4">
            <FileSearch size={32} />
          </div>
          <h2 className="font-sans font-bold text-2xl text-slate-800 mb-2">No Report Selected</h2>
          <p className="font-sans text-slate-500 mb-8 max-w-md mx-auto">
            You are not currently viewing any experiment. Run a new pipeline or select a past experiment from the Home dashboard.
          </p>
          <Link href="/run">
            <Button className="bg-cyan-600 hover:bg-cyan-700 text-white">
              Run Experiment
            </Button>
          </Link>
        </div>
      </PageWrapper>
    )
  }

  return (
    <PageWrapper>
      <div className="max-w-6xl mx-auto w-full">
        <div className="mb-6">
          <h1 className="font-sans font-bold text-3xl text-slate-800 mb-2">Automated Research Report</h1>
          <p className="font-sans text-sm text-slate-500">
            Generated by the AIRO Reporter Agent upon pipeline completion.
          </p>
        </div>

        {loading ? (
          <div className="w-full p-20 flex flex-col items-center justify-center text-slate-400 bg-white border border-slate-100 rounded-2xl shadow-sm">
            <Loader2 className="animate-spin mb-4" size={32} />
            <p className="font-mono text-sm">Fetching report data...</p>
          </div>
        ) : error || !content ? (
          <div className="w-full p-12 bg-red-50 border border-red-100 rounded-2xl text-center text-red-600">
            <p className="font-sans font-semibold mb-2">Report not found</p>
            <p className="text-sm opacity-80">The requested report could not be loaded or has not been generated yet.</p>
          </div>
        ) : (
          <>
            <MarkdownViewer content={content} experimentId={targetId} />
            <InteractiveCharts experimentId={targetId} />
          </>
        )}
      </div>
    </PageWrapper>
  )
}

export default function ReportPage() {
  return (
    <Suspense fallback={<div className="p-12 text-center text-slate-400 font-mono">Loading...</div>}>
      <ReportContent />
    </Suspense>
  )
}
